### ISSUE TITLE
npm doesn't work 

### ISSUE THREAD

**Issue by danieltepavac** [danieltepavac/BundestagsMediathek#12]
npm ERR! code EPERM
npm ERR! syscall open
npm ERR! path C:\Windows\package-lock.json
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, open 'C:\Windows\package-lock.json'
npm ERR!  [Error: EPERM: operation not permitted, open 'C:\Windows\package-lock.json'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Windows\\package-lock.json'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Daniel Tepavac\AppData\Local\npm-cache\_logs\2022-09-01T10_00_49_540Z-debug-0.log

**Comment by conpat** [comment]
Lag an der Linux Umgebung und funktioniert auf Windows nativ
